version: '3'
services:
  elasticsearch:
    build: elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    expose:
      - 9300
    networks:
      - elastic
  kibana:
    build: kibana
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elastic
volumes:
  es-data:
    driver: local
networks:
  elastic:
    driver: bridge

